import pandas as pd

from pathlib import Path
from html import escape


# Map internal detection identifiers to professional,
# human-readable labels for the security analysis report.
DETECTION_LABELS = {
    'brute_force': 'Brute-Force Activity',
    'password_spraying': 'Password-Spraying Activity',
    'success_after_failures': 'Successful Login After Repeated Failures'
}


def build_analysis_summary(auth_logs, alerts):
    '''
    Build summary metrics for the authentication security analysis.

    The summary is derived from the authentication events and the
    structured alerts produced by the detection engine. It does not
    perform or modify any detection logic.
    '''

    # Count the total number of authentication events analyzed.
    total_events = len(auth_logs)

    # Count the number of structured alerts generated by all
    # detection rules.
    total_alerts = len(alerts)

    # Count each type of detection independently so the report can
    # summarize the distribution of generated alerts.
    detection_counts = {
        'brute_force': 0,
        'password_spraying': 0,
        'success_after_failures': 0
    }

    for alert in alerts:
        detection = alert['detection']

        if detection in detection_counts:
            detection_counts[detection] += 1

    # Collect the unique source IP addresses represented in alerts.
    # Every current detection type includes a source_ip field.
    source_ips = {
        alert['source_ip']
        for alert in alerts
        if 'source_ip' in alert
    }

    # Collect affected usernames across detection types.
    # Some alerts contain one username, while password-spraying
    # alerts contain a list of targeted usernames.
    affected_usernames = set()

    for alert in alerts:

        if 'username' in alert:
            affected_usernames.add(
                alert['username']
            )

        if 'usernames' in alert:
            affected_usernames.update(
                alert['usernames']
            )

    return {
        'total_events': total_events,
        'total_alerts': total_alerts,
        'unique_source_ips': len(source_ips),
        'affected_accounts': len(affected_usernames),
        'detection_counts': detection_counts
    }


def build_authentication_timeline(auth_logs, alert):
    '''
    Build a chronological authentication-event timeline for one
    generated security alert.

    The timeline includes only authentication activity associated
    with the entities represented by the supplied alert.
    '''

    # Brute-force and success-after-failures alerts identify one
    # username and source-IP combination.
    if 'username' in alert:

        relevant_events = auth_logs[
            (auth_logs['username'] == alert['username'])
            & (auth_logs['source_ip'] == alert['source_ip'])
        ]

    # Password-spraying alerts identify multiple usernames
    # targeted by one source IP.
    elif 'usernames' in alert:

        relevant_events = auth_logs[
            (auth_logs['username'].isin(alert['usernames']))
            & (auth_logs['source_ip'] == alert['source_ip'])
        ]

    # If a future alert type does not identify accounts in either
    # supported format, return an empty timeline rather than
    # including unrelated authentication activity.
    else:
        relevant_events = auth_logs.iloc[0:0]

    # Restrict the timeline to the detection's relevant time range.
    # Alerts contain timestamps identifying the first failure and
    # the final event associated with the detected activity.
    if (
        pd.notna(alert.get('first_failure'))
        and pd.notna(alert.get('last_failure'))
    ):

        # A successful-login-after-failures detection ends with
        # the successful authentication, not the last failure.
        end_time = alert.get(
            'success_time',
            alert['last_failure']
        )

        relevant_events = relevant_events[
            (relevant_events['timestamp'] >= alert['first_failure'])
            & (relevant_events['timestamp'] <= end_time)
        ]

    # Keep only the fields needed for report visualization.
    timeline = relevant_events[
        [
            'timestamp',
            'username',
            'source_ip',
            'status'
        ]
    ].copy()

    # Sort relevant events chronologically.
    timeline = timeline.sort_values(
        'timestamp'
    ).reset_index(drop=True)

    # Create a readable event label for report presentation.
    timeline['event_label'] = (
        timeline['username']
        + ' — '
        + timeline['status']
    )

    return timeline


def get_detection_label(detection):
    '''
    Return a human-readable label for an authentication detection.

    Unknown detection identifiers receive a readable fallback,
    allowing future detection rules to use the same reporting layer.
    '''

    # Use the predefined label when the detection type is known.
    if detection in DETECTION_LABELS:
        return DETECTION_LABELS[detection]

    # Convert an unknown identifier into a readable label.
    return detection.replace('_', ' ').title()


def get_detection_methodology(detection):
    '''
    Return a description of the rule used to identify
    a particular authentication anomaly.

    These descriptions document existing detection logic.
    They do not execute or modify the detection rules.
    '''

    methodologies = {
        'brute_force': (
            'Identifies repeated failed authentication attempts '
            'against the same account from the same source IP '
            'address. A detection is generated when at least '
            'five failures occur within a ten-minute window.'
        ),

        'password_spraying': (
            'Identifies failed authentication attempts originating '
            'from the same source IP address against multiple '
            'distinct accounts. A detection is generated when '
            'at least five unique accounts are targeted within '
            'a ten-minute window.'
        ),

        'success_after_failures': (
            'Identifies a successful authentication following '
            'repeated failed attempts against the same account '
            'from the same source IP address. A detection is '
            'generated when a successful login follows at least '
            'five failures within the preceding ten minutes.'
        )
    }

    # Return the methodology for a recognized detection rule.
    # Unknown rules receive a neutral fallback description.
    return methodologies.get(
        detection,
        'No methodology description is available for this detection.'
    )


def get_analyst_interpretation(detection):
    '''
    Return a security-focused interpretation of an authentication
    anomaly without treating suspicious activity as confirmed compromise.

    Interpretations identify potential security implications and
    recommend appropriate investigative follow-up.
    '''

    interpretations = {
        'brute_force': (
            'Repeated authentication failures against a single account '
            'may indicate password guessing or an automated credential '
            'attack. However, legitimate user errors or misconfigured '
            'applications can produce similar patterns. Review the '
            'source IP, affected account, authentication history, and '
            'related security events to determine whether the activity '
            'warrants further investigation.'
        ),

        'password_spraying': (
            'Failed authentication attempts against multiple accounts '
            'from a common source IP may indicate password spraying, '
            'in which an attacker attempts a small number of passwords '
            'across many accounts. Shared infrastructure or legitimate '
            'automated processes may produce similar activity. Review '
            'the source IP, targeted accounts, timing, and subsequent '
            'authentication outcomes to assess potential exposure.'
        ),

        'success_after_failures': (
            'A successful authentication following repeated failures '
            'may indicate that a credential-guessing attempt succeeded. '
            'However, it may also represent a legitimate user entering '
            'the correct password after several mistakes. This pattern '
            'warrants closer examination of the successful session, '
            'including device information, geographic context, MFA '
            'results, and subsequent account activity where available. '
            'The detection alone does not establish account compromise.'
        )
    }

    # Return the interpretation associated with the detection.
    # Unknown detection types receive a neutral fallback.
    return interpretations.get(
        detection,
        'No analyst interpretation is available for this detection.'
    )


def escape_html_value(value):
    '''
    Convert a value into HTML-safe text.

    Escapes special HTML characters so authentication log data
    is displayed as text rather than interpreted as markup.
    '''

    # Convert values such as integers and pandas timestamps
    # into strings before applying HTML escaping.
    return escape(str(value), quote=True)


def get_authentication_status_class(status):
    '''
    Return a recognized CSS class for an authentication status.

    Only explicitly supported authentication outcomes may be
    used as status-specific CSS classes.
    '''

    # Define the authentication outcomes supported by the report.
    allowed_statuses = {
        'success',
        'failure'
    }

    # Return the original status only when it is recognized.
    if status in allowed_statuses:
        return status

    # Assign a neutral class to unexpected authentication statuses.
    return 'unknown'


def build_detection_evidence(alert):
    '''
    Prepare human-readable evidence fields for a security alert.

    The function uses evidence already produced by the detection
    engine. It does not recalculate or modify detection results.
    '''

    # Include evidence fields common to all current detections.
    evidence = {
        'Severity': alert.get('severity', 'unknown').title(),
        'Source IP': alert.get('source_ip', 'Not available'),
        'Detection Window': alert.get('window', 'Not available')
    }

    # Add evidence specific to brute-force detections.
    if alert['detection'] == 'brute_force':

        evidence['Target Account'] = alert.get(
            'username',
            'Not available'
        )

        evidence['Failed Attempts'] = alert.get(
            'failure_count',
            'Not available'
        )

    # Add evidence specific to password-spraying detections.
    elif alert['detection'] == 'password_spraying':

        evidence['Accounts Targeted'] = alert.get(
            'unique_user_count',
            'Not available'
        )

        evidence['Targeted Usernames'] = ', '.join(
            alert.get('usernames', [])
        )

    # Add evidence specific to successful logins following failures.
    elif alert['detection'] == 'success_after_failures':

        evidence['Target Account'] = alert.get(
            'username',
            'Not available'
        )

        evidence['Preceding Failures'] = alert.get(
            'failure_count',
            'Not available'
        )

        evidence['Successful Login'] = alert.get(
            'success_time',
            'Not available'
        )

    # Include the observed failure timestamps when available.
    evidence['First Failure'] = alert.get(
        'first_failure',
        'Not available'
    )

    evidence['Last Failure'] = alert.get(
        'last_failure',
        'Not available'
    )

    return evidence

def generate_html_report(auth_logs, alerts, output_path):
    '''
    Generate a self-contained HTML authentication security report.

    The report summarizes the completed authentication analysis and
    presents the results in a format suitable for analyst review.
    '''

    # Normalize the output path so the function can accept either
    # a Path object or a path-like string.
    output_path = Path(output_path)

    # Build the tested summary metrics from the authentication
    # events and structured detection alerts.
    summary = build_analysis_summary(
        auth_logs,
        alerts
    )

        # Build a separate investigation timeline for each generated
    # security alert rather than combining unrelated detections.
    alert_timelines = []

    for alert in alerts:

        # Prepare authentication events associated with this alert.
        timeline = build_authentication_timeline(
            auth_logs,
            alert
        )

        timeline_rows = []

        for _, event in timeline.iterrows():
            get_detection_label
            # Format the timestamp for human-readable presentation.
            timestamp = event['timestamp'].strftime(
                '%Y-%m-%d %H:%M:%S'
            )

            # Escape all authentication data before inserting it
            # into HTML. These values originate from CSV input.
            safe_timestamp = escape_html_value(timestamp)
            safe_event_label = escape_html_value(event['event_label'])
            safe_source_ip = escape_html_value(event['source_ip'])
            
            # Restrict authentication status CSS classes to recognized values.
            safe_status = get_authentication_status_class(
                event['status']
            )

            # Render the authentication event using only
            # HTML-safe values.
            timeline_rows.append(
                f'''
                <div class="timeline-event {safe_status}">
                    <div class="timeline-marker"></div>

                    <div class="timeline-content">
                        <div class="timeline-time">
                            {safe_timestamp}
                        </div>

                        <div class="timeline-title">
                            {safe_event_label}
                        </div>

                        <div class="timeline-source">
                            Source IP: {safe_source_ip}
                        </div>
                    </div>
                </div>
                '''
            )

        # Combine the event rows for this individual alert.
        events_html = '\n'.join(timeline_rows)

        # Use consistent, human-readable detection terminology.
        detection_name = get_detection_label(
            alert['detection']
        )

        # Extract the evidence already collected by the detection engine.
        evidence = build_detection_evidence(alert)

        # Convert each evidence field into an HTML row.
        evidence_rows = []

        for label, value in evidence.items():

            # Escape both the evidence label and its value before
            # inserting them into the generated HTML document.
            safe_label = escape_html_value(label)
            safe_value = escape_html_value(value)

            evidence_rows.append(
                f'''
                <div class="evidence-item">
                    <span class="evidence-label">{safe_label}</span>
                    <span class="evidence-value">{safe_value}</span>
                </div>
                '''
            )

        # Combine the evidence rows into one HTML fragment.
        evidence_html = '\n'.join(evidence_rows)

        # Retrieve the methodology associated with this detection.
        # Escape the description before inserting it into HTML.
        methodology = get_detection_methodology(
            alert['detection']
        )

        safe_methodology = escape_html_value(methodology)

        # Retrieve the security interpretation for this detection.
        # Escape the text before inserting it into the HTML report.
        interpretation = get_analyst_interpretation(
            alert['detection']
        )

        safe_interpretation = escape_html_value(interpretation)

        # Keep each alert's timeline in its own report section.
        alert_timelines.append(
            f'''
            <div class="alert-timeline">
                <h3>{detection_name}</h3>

                <div class="evidence-grid">
                    {evidence_html}
                </div>

                <div class="methodology-panel">
                    <h4>Detection Methodology</h4>
                    <p>{safe_methodology}</p>
                </div>
                
                <div class="interpretation-panel">
                    <h4>Analyst Interpretation</h4>
                    <p>{safe_interpretation}</p>
                </div>

                <div class="timeline">
                    {events_html}
                </div>
            </div>
            '''
        )

    # Combine all individual investigation timelines into
    # one HTML fragment for the report.
    timeline_html = '\n'.join(alert_timelines)

    # Identify the largest detection count so each visual bar can
    # be scaled relative to the most frequent detection type.
    max_detection_count = max(
        summary['detection_counts'].values(),
        default=0
    )

    # Prevent division by zero when the analysis produces no alerts.
    if max_detection_count == 0:
        max_detection_count = 1

    # Convert detection counts into relative percentages for the
    # report's horizontal bar visualization.
    detection_percentages = {
        detection: (
            count / max_detection_count
        ) * 100
        for detection, count
        in summary['detection_counts'].items()
    }

    # Create the destination directory when it does not already
    # exist.
    output_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    # Build the initial HTML document. Later iterations will add
    # visual analysis, detection details, and methodology sections.
    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
    >
    <title>Authentication Security Analysis Report</title>

    <style>
        /* ---------- Global Styling ---------- */

        * {{
            box-sizing: border-box;
        }}

        body {{
            margin: 0;
            background: #f3f5f7;
            color: #24303d;
            font-family:
                -apple-system,
                BlinkMacSystemFont,
                "Segoe UI",
                Arial,
                sans-serif;
            line-height: 1.5;
        }}

        main {{
            width: min(1180px, calc(100% - 48px));
            margin: 40px auto;
            padding: 48px;
            background: #ffffff;
            border: 1px solid #dfe4e8;
            border-radius: 10px;
            box-shadow: 0 8px 24px rgba(20, 34, 48, 0.08);
        }}

        /* ---------- Report Header ---------- */

        header {{
            padding-bottom: 28px;
            margin-bottom: 36px;
            border-bottom: 3px solid #17324d;
        }}

        header h1 {{
            margin: 0 0 10px;
            color: #17324d;
            font-size: 32px;
            font-weight: 700;
            letter-spacing: -0.5px;
        }}

        header p {{
            margin: 0;
            color: #65717d;
            font-size: 16px;
        }}

        /* ---------- Report Sections ---------- */

        section {{
            margin-top: 40px;
        }}

        section > h2 {{
            margin: 0 0 20px;
            color: #17324d;
            font-size: 22px;
            font-weight: 700;
        }}

        .section-description {{
            margin: -8px 0 24px;
            color: #65717d;
            font-size: 14px;
        }}

        /* ---------- Executive Summary ---------- */

        .summary-grid {{
            display: grid;
            grid-template-columns: repeat(4, minmax(0, 1fr));
            gap: 16px;
            margin-top: 24px;
        }}

        .summary-card {{
            min-height: 110px;
            padding: 20px;
            background: #f8fafb;
            border: 1px solid #dfe4e8;
            border-radius: 8px;
        }}

        .summary-card h3 {{
            margin: 0 0 10px;
            color: #65717d;
            font-size: 13px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }}

        .summary-card p {{
            margin: 0;
            color: #17324d;
            font-size: 30px;
            font-weight: 700;
        }}

        /* ---------- Detection Overview ---------- */

        .detection-chart {{
            display: flex;
            flex-direction: column;
            gap: 20px;
            margin-top: 24px;
            padding: 24px;
            background: #f8fafb;
            border: 1px solid #dfe4e8;
            border-radius: 8px;
        }}

        .detection-row {{
            display: grid;
            grid-template-columns: 190px minmax(0, 1fr) 40px;
            align-items: center;
            gap: 16px;
        }}

        .detection-label {{
            color: #24303d;
            font-size: 14px;
            font-weight: 600;
        }}

        .bar-track {{
            width: 100%;
            height: 14px;
            overflow: hidden;
            background: #e5eaf0;
            border-radius: 7px;
        }}

        .bar {{
            height: 100%;
            min-width: 0;
            background: #416783;
            border-radius: 7px;
        }}

        .detection-count {{
            color: #17324d;
            font-size: 15px;
            font-weight: 700;
            text-align: right;
        }}

        /* ---------- Investigation Cards ---------- */

        .alert-timeline {{
            margin-top: 24px;
            padding: 28px;
            background: #ffffff;
            border: 1px solid #dfe4e8;
            border-left: 4px solid #17324d;
            border-radius: 8px;
        }}

        .alert-timeline > h3 {{
            margin: 0 0 24px;
            color: #17324d;
            font-size: 19px;
            font-weight: 700;
        }}

        /* ---------- Detection Evidence ---------- */

        .evidence-grid {{
            display: grid;
            grid-template-columns: repeat(
                auto-fit,
                minmax(200px, 1fr)
            );
            gap: 20px;
            margin: 0 0 28px;
            padding: 22px;
            background: #f8fafb;
            border: 1px solid #dfe4e8;
            border-radius: 8px;
        }}

        .evidence-item {{
            display: flex;
            flex-direction: column;
            gap: 5px;
            min-width: 0;
        }}

        .evidence-label {{
            color: #65717d;
            font-size: 12px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }}

        .evidence-value {{
            color: #24303d;
            font-size: 14px;
            font-weight: 600;
            overflow-wrap: anywhere;
        }}

        /* ---------- Methodology and Interpretation ---------- */

        .methodology-panel,
        .interpretation-panel {{
            margin-bottom: 24px;
            padding: 20px 22px;
            background: #f8fafb;
            border: 1px solid #dfe4e8;
            border-radius: 8px;
        }}

        .methodology-panel {{
            border-left: 3px solid #416783;
        }}

        .interpretation-panel {{
            border-left: 3px solid #66788a;
        }}

        .methodology-panel h4,
        .interpretation-panel h4 {{
            margin: 0 0 10px;
            color: #17324d;
            font-size: 15px;
            font-weight: 700;
        }}

        .methodology-panel p,
        .interpretation-panel p {{
            margin: 0;
            color: #52606d;
            font-size: 14px;
            line-height: 1.65;
        }}

        /* ---------- Authentication Timeline ---------- */

        .timeline {{
            position: relative;
            margin-top: 28px;
            padding-left: 24px;
            border-left: 2px solid #dfe4e8;
        }}

        .alert-timeline > .timeline {{
            margin-bottom: 4px;
        }}

        .timeline-event {{
            position: relative;
            padding: 0 0 20px 24px;
        }}

        .timeline-event:last-child {{
            padding-bottom: 0;
        }}

        .timeline-marker {{
            position: absolute;
            top: 5px;
            left: -31px;
            width: 12px;
            height: 12px;
            background: #66788a;
            border: 2px solid #ffffff;
            border-radius: 50%;
            box-shadow: 0 0 0 2px #dfe4e8;
        }}

        .timeline-event.failure .timeline-marker {{
            background: #b54747;
        }}

        .timeline-event.success .timeline-marker {{
            background: #2f7d5a;
        }}

        .timeline-content {{
            padding: 14px 16px;
            background: #f8fafb;
            border: 1px solid #dfe4e8;
            border-radius: 8px;
        }}

        .timeline-time {{
            margin-bottom: 4px;
            color: #65717d;
            font-size: 12px;
        }}

        .timeline-title {{
            color: #17324d;
            font-size: 15px;
            font-weight: 600;
        }}

        .timeline-source {{
            margin-top: 4px;
            color: #65717d;
            font-size: 13px;
        }}

        /* ---------- Responsive Layout ---------- */

        @media (max-width: 900px) {{
            .summary-grid {{
                grid-template-columns: repeat(2, minmax(0, 1fr));
            }}
        }}

        @media (max-width: 650px) {{
            main {{
                width: calc(100% - 24px);
                margin: 12px auto;
                padding: 24px;
            }}

            header h1 {{
                font-size: 26px;
            }}

            .summary-grid {{
                grid-template-columns: 1fr;
            }}

            .detection-row {{
                grid-template-columns: 1fr;
                gap: 8px;
            }}

            .detection-count {{
                text-align: left;
            }}

            .detection-chart {{
                padding: 18px;
            }}

            .alert-timeline {{
                padding: 20px;
            }}

            .evidence-grid {{
                grid-template-columns: 1fr;
            }}
        }}
    </style>
</head>

<body>
    <main>

        <!-- ---------- Report Header ---------- -->

        <header>
            <h1>Authentication Security Analysis Report</h1>
            <p>
                Security analysis of structured authentication events
                using rule-based anomaly detection.
            </p>
        </header>

        <!-- ---------- Executive Summary ---------- -->

        <section>
            <h2>Executive Summary</h2>

            <div class="summary-grid">

                <div class="summary-card">
                    <h3>Events Analyzed</h3>
                    <p>{summary['total_events']}</p>
                </div>

                <div class="summary-card">
                    <h3>Alerts Generated</h3>
                    <p>{summary['total_alerts']}</p>
                </div>

                <div class="summary-card">
                    <h3>Affected Accounts</h3>
                    <p>{summary['affected_accounts']}</p>
                </div>

                <div class="summary-card">
                    <h3>Source IPs</h3>
                    <p>{summary['unique_source_ips']}</p>
                </div>

            </div>
        </section>

        <!-- ---------- Detection Overview ---------- -->

        <section>
            <h2>Detection Overview</h2>

            <p class="section-description">
                Alerts generated by each authentication anomaly
                detection rule.
            </p>

            <div class="detection-chart">

                <div class="detection-row">
                    <div class="detection-label">
                        Brute Force
                    </div>

                    <div class="bar-track">
                        <div
                            class="bar"
                            style="width: {detection_percentages['brute_force']}%;"
                        ></div>
                    </div>

                    <div class="detection-count">
                        {summary['detection_counts']['brute_force']}
                    </div>
                </div>

                <div class="detection-row">
                    <div class="detection-label">
                        Password Spraying
                    </div>

                    <div class="bar-track">
                        <div
                            class="bar"
                            style="width: {detection_percentages['password_spraying']}%;"
                        ></div>
                    </div>

                    <div class="detection-count">
                        {summary['detection_counts']['password_spraying']}
                    </div>
                </div>

                <div class="detection-row">
                    <div class="detection-label">
                        Success After Failures
                    </div>

                    <div class="bar-track">
                        <div
                            class="bar"
                            style="width: {detection_percentages['success_after_failures']}%;"
                        ></div>
                    </div>

                    <div class="detection-count">
                        {summary['detection_counts']['success_after_failures']}
                    </div>
                </div>

            </div>
        </section>

        <!-- ---------- Authentication Investigations ---------- -->

        <section>
            <h2>Authentication Event Timeline</h2>

            <p class="section-description">
                Authentication activity associated with each generated
                detection. Evidence, detection methodology, analyst
                interpretation, and chronological events are presented
                together to support investigation.
            </p>

            {timeline_html}

        </section>

    </main>
</body>
</html>
'''

    # Write the complete report as a UTF-8 encoded HTML file.
    output_path.write_text(
        html,
        encoding='utf-8'
    )


